export enum EModal {
  MODAL_EDIT_PRODUCT = "MODAL_EDIT_PRODUCT",
  MODAL_DELETE_PRODUCT = "MODAL_DELETE_PRODUCT",
  UNSAVE_CHANGE_PRODUCT = "UNSAVE_CHANGE_PRODUCT",
  UPLOAD_IMAGE_MODAL = "UPLOAD_IMAGE_MODAL",
}

export enum ECloudinary {
  CLOUDINARY_CLOUD_NAME = "ptd",
  CLOUDINARY_API_KEY = "151112439555433",
  CLOUDINARY_API_SECRET = "qyg4I25IzyoC7AGE7VI5X9MW-og",
  CLOUDINARY_UPLOAD_PRESET = "cpfzdjwo",
}

export enum ETelegram {
  CHAT_ID = "5950892264",
  API_KEY = "7183090222:AAHyjXNm7ivANYL_TTOCtV1rbsTSJB4cNB4",
}
